const fs=require("fs");const{JSDOM,VirtualConsole}=require("jsdom");
const html=fs.readFileSync(process.argv[2]||"public/index.html","utf8");
const hatalar=[];
const vc=new VirtualConsole();vc.on("jsdomError",e=>{hatalar.push("jsdomError: "+e.message);console.log("!!",e.message);});
const dom=new JSDOM(html,{runScripts:"dangerously",url:"http://localhost/",pretendToBeVisual:true,virtualConsole:vc,
 beforeParse(w){
  w.Path2D=class{moveTo(){}lineTo(){}closePath(){}};
  w.ResizeObserver=class{observe(){}disconnect(){}};
  w.fetch=()=>Promise.reject(new Error("ağ-yok"));
  w.WebSocket=class{constructor(){this.readyState=3}close(){}send(){}};
  w.HTMLCanvasElement.prototype.getContext=()=>null;
  w.requestAnimationFrame=f=>setTimeout(f,0);w.scrollTo=()=>{};
  w.addEventListener("error",e=>{hatalar.push("pencere: "+e.message);console.log("!!",e.message);});
 }});
setTimeout(()=>{
 const w=dom.window,d=w.document,E=s=>w.eval(s);
 const dene=(ad,f)=>{try{f();console.log("✓",ad);}catch(e){hatalar.push(ad+": "+e.message);console.log("✗",ad,e.message);}};
 dene("v4 sürüm",()=>{if(E("DATA.surum")!=="4.0")throw Error(E("DATA.surum"));});
 dene("ada kataloğu ≥110",()=>{if(E("GEO.ada.length")<110)throw Error(E("GEO.ada.length"));});
 dene("isimli ada ≥105",()=>{const n=E("GEO.ada.filter(a=>a.ad).length");if(n<105)throw Error(n);});
 dene("ada bul: Kilimli",()=>{const a=E('ADA.bul(26.97,37.01)');if(!a||a.ad!=="Kilimli")throw Error(JSON.stringify(a&&a.ad));});
 dene("ada bul: Keçi Adası",()=>{const a=E('ADA.bul(27.148,36.933)');if(!a||a.ad!=="Keçi Adası")throw Error(a&&a.ad);});
 dene("ada bul: Kardak=IHT",()=>{const a=E('ADA.bul(27.1532,37.0545)');if(!a||a.c!=="IHT")throw Error(JSON.stringify(a));});
 dene("ada kartı: alan+mesafe",()=>{E('ADA.kart(ADA.bul(29.59,36.15),90,90)');const t=d.getElementById("hk-govde").textContent;
  if(!/km²/.test(t)||!/Türk anakarasına/.test(t))throw Error(t.slice(0,60));
  if(!d.getElementById("hk-baslik").textContent.includes("Meis"))throw Error(d.getElementById("hk-baslik").textContent);});
 dene("adaya tıkla → kart",()=>{E("HARITA.git(27.148,36.933,9)");const ok=E("(()=>{const[px,py]=HARITA.ekran(27.148,36.933);POP.sonda(27.148,36.933,px,py);return document.getElementById('hk-baslik').textContent})()");
  if(!ok.includes("Keçi"))throw Error(ok);});
 dene("isimsiz adacık da bilgi verir",()=>{const a=E("GEO.ada.find(a=>!a.ad)");if(!a)return;E(`ADA.kart(GEO.ada.find(a=>!a.ad),80,80)`);
  const t=d.getElementById("hk-govde").textContent;if(!/km²/.test(t))throw Error("bilgi yok");
  if(!d.getElementById("hk-baslik").textContent.includes("Adı kayıtlı değil"))throw Error(d.getElementById("hk-baslik").textContent);});
 dene("rejim: Onikiada",()=>{const r=E('ADA.rejim(ADA.bul(27.09,36.80))');if(!/Onikiada/.test(r.b))throw Error(r.b);});
 dene("rejim: EGAYDAAK",()=>{const r=E('ADA.rejim(ADA.bul(27.1532,37.0545))');if(!/ihtilafl/.test(r.b))throw Error(r.b);});
 dene("SİM filo üretiyor",()=>{const f=E("SIM.filo()");if(f.length<20)throw Error("uçak "+f.length);
  if(!f[0].cs||f[0].lat<30||f[0].lat>46)throw Error(JSON.stringify(f[0]));});
 dene("SİM hareket ediyor",()=>{const a=E("SIM.filo()[0].lon");E("Date.now=(()=>{const o=Date.now;let t=o();return()=>t+600000})()");
  const b=E("SIM.filo()[0].lon");if(Math.abs(a-b)<0.01)throw Error("kıpırdamadı");});
 dene("uçak katmanı → SİM'e düşüyor",()=>{E('AYAR.ucusKaynak="oto"');E('KATMAN.ac("ucak",1)');
  E("CANLI.hata('test')");if(E("AYAR.ucusKaynak")!=="sim")throw Error("otomatik geçiş yok");
  if(!E("CANLI.ucaklar.length"))throw Error("uçak yok");});
 dene("uçak HUD",()=>{const h=d.getElementById("ucus-hud");if(!h)throw Error("hud yok");
  if(!/SİMÜLASYON/.test(h.textContent))throw Error(h.textContent);});
 dene("uçağa tıkla → kart",()=>{E("HARITA.git(CANLI.ucaklar[0].lon,CANLI.ucaklar[0].lat,7)");
  const ok=E("(()=>{const u=CANLI.ucaklar[0];const[px,py]=HARITA.ekran(u.lon,u.lat);return TIKLA_EK(u.lon,u.lat,px,py)})()");
  if(!ok)throw Error("isabet yok");const t=d.getElementById("hk-govde").textContent;
  if(!/İrtifa/.test(t)||!/FIR/.test(t))throw Error(t.slice(0,70));E('KATMAN.ac("ucak",0)');});
 dene("OAuth2 alanları",()=>{if(!d.getElementById("ay-osi")||!d.getElementById("ay-oss")||!d.getElementById("ay-ucus"))throw Error("ayar alanı yok");
  if(E("typeof OS.tokenAl")!=="function")throw Error("token fonksiyonu yok");});
 dene("Basic auth kaldırıldı",()=>{if(/Basic \"\+btoa/.test(E("CANLI.osFetch.toString()")))throw Error("hâlâ Basic auth");});
 dene("kapsam dışı uyarısı",()=>{E("HARITA.git(-45,-60,5)");E("kapsamDenetle()");
  if(!d.getElementById("kapsam-uyari").classList.contains("acik"))throw Error("uyarı çıkmadı");
  E("HARITA.git(27.5,38.2,5.6)");E("kapsamDenetle()");
  if(d.getElementById("kapsam-uyari").classList.contains("acik"))throw Error("uyarı kapanmadı");});
 dene("v3 sürüm alanı",()=>{if(E("DATA.surum")!=="4.0")throw Error("sürüm");});
 dene("GEO.parts + sov",()=>{if(E("GEO.parts.length")<150)throw Error("parça az: "+E("GEO.parts.length"));if(!E('GEO.sov.OSM'))throw Error("sov yok");});
 dene("sovKod 1800 Atina=OSM",()=>{const r=E('(()=>{const P=GEO.parts.find(p=>HARITA.poliIcinde([23.73,37.98],p.p));return HARITA.sovKod(P.t,1800)})()');if(r!=="OSM")throw Error(r);});
 dene("sovKod 2026 Atina=GR",()=>{const r=E('(()=>{const P=GEO.parts.find(p=>HARITA.poliIcinde([23.73,37.98],p.p));return HARITA.sovKod(P.t,2026)})()');if(r!=="GR")throw Error(r);});
 dene("1800 İstanbul=OSM",()=>{const r=E('(()=>{const P=GEO.parts.find(p=>HARITA.poliIcinde([28.98,41.01],p.p));return HARITA.sovKod(P.t,1800)})()');if(r!=="OSM")throw Error(r);});
 dene("1930 Meis=İtalya",()=>{const r=E('HARITA.sovKod(DATA.adalar.find(a=>a.id==="meis").t,1930)');if(r!=="IT")throw Error(r);});
 dene("1960 Kıbrıs=CY",()=>{const r=E('HARITA.sovKod(DATA.adalar.find(a=>a.id==="kibris").t,1960)');if(r!=="CY")throw Error(r);});
 dene("Kardak IHT",()=>{const r=E('HARITA.sovKod(DATA.adalar.find(a=>a.id==="kardak").t,2026)');if(r!=="IHT")throw Error(r);});
 dene("yeni adalar var",()=>{for(const id of["pserimos","fournoi","ro","strongili","korfu","kitira","imrali","milos"])if(!E(`DATA.adalar.some(a=>a.id==="${id}")`))throw Error(id);});
 dene("ada sayısı ≥55",()=>{if(E("DATA.adalar.length")<55)throw Error(E("DATA.adalar.length"));});
 dene("kaydırıcı 1780",()=>{if(d.getElementById("zaman-kaydirici").min!=="1780")throw Error(d.getElementById("zaman-kaydirici").min);});
 dene("egemenlik lejantı",()=>{E("ZAMAN.ayarla(1800)");const n=d.querySelectorAll("#sov-lejant .lej").length;if(n<3)throw Error("lej "+n);
  const ad=d.querySelector("#sov-lejant .lej").textContent;if(!ad.includes("Osmanlı"))throw Error(ad);E("ZAMAN.ayarla(2026)");});
 dene("dönem seçici",()=>{const s=d.getElementById("zb-donem");s.value="1913";s.dispatchEvent(new w.Event("change"));if(d.getElementById("zaman-yil").textContent!=="1913")throw Error("atlamadı");E("ZAMAN.ayarla(2026)");});
 dene("sonda: kara tarihsel",()=>{E("POP.sonda(23.73,37.98,120,120)");const t=d.getElementById("hk-govde").textContent;if(!/Osmanlı/.test(t))throw Error(t.slice(0,60));});
 dene("ada kartı egemenlik geçmişi",()=>{E('POP.ada(DATA.adalar.find(a=>a.id==="meis"),100,100)');const t=d.getElementById("hk-govde").textContent;
  if(!/İtalya/.test(t)||!/Egemenlik geçmişi/.test(t))throw Error(t.slice(0,80));});
 dene("SAR 25. meridyen",()=>{const c=E("DATA.cizimler.sarTR");if(Math.abs(c[0][0][0]-25)>0.01)throw Error("başlangıç "+c[0][0][0]);});
 dene("Zaman Makinesi turu",()=>{E('TUR.basla("tarih")');if(d.getElementById("zaman-yil").textContent!=="1800")throw Error("1800 değil");
  for(let i=0;i<7;i++)E("TUR.ileri()");if(d.getElementById("zaman-yil").textContent!=="2026")throw Error("son adım "+d.getElementById("zaman-yil").textContent);E("TUR.bitir()");});
 dene("uzman kilidi",()=>{if(d.documentElement.dataset.seviye!=="uzman")throw Error("değil");});
 for(const id of ["harita","zaman","antlasmalar","adalar","tezler","krizler","guncel","operasyon","test","sozluk","kaynakca","yardim"])dene("modül "+id,()=>E(`MOD.git("${id}")`));
 dene("antlaşma tek blok",()=>{if(d.querySelector('#ant-liste [data-lv="l"]'))throw Error("çift blok kaldı");});
 dene("güncel §not",()=>{if(!d.querySelector("#ic-guncel .unot"))throw Error("unot yok");});
 dene("quiz 16 soru",()=>{E('MOD.git("test")');if(!/1\/16|1\s*\/\s*16/.test(d.querySelector("#soru-alan").textContent))throw Error(d.querySelector("#soru-alan").textContent.slice(0,40));});
 dene("yeni katmanlar",()=>{for(const id of["esas","mebKdz","tpao","kibKuzey"])if(!E(`KATMAN.liste.some(k=>k.id==="${id}")`))throw Error(id+" yok");});
 dene("yıl kapısı alanı",()=>{if(E('KATMAN.liste.find(k=>k.id==="libya").yil')!==2019)throw Error("yıl yok");});
 dene("zaman tikleri",()=>{if(d.querySelectorAll("#zaman-tikler .z-tik").length<25)throw Error("tik az");if(!d.getElementById("zb-ileri"))throw Error("ileri yok");});
 dene("zaman atla ⏭",()=>{E("ZAMAN.ayarla(1900)");d.getElementById("zb-ileri").click();if(+d.getElementById("zaman-yil").textContent<=1900)throw Error("atlamadı");E("ZAMAN.ayarla(2026)");});
 dene("çizgi tıklama (Libya)",()=>{E("HARITA.git(26.5,34.21,7)");const ok=E("(()=>{const[px,py]=HARITA.ekran(26.45,34.23);return TIKLA_EK(26.45,34.23,px,py)})()");
  if(!ok)throw Error("isabet yok");if(!d.getElementById("hk-baslik").textContent.includes("Libya"))throw Error("kart: "+d.getElementById("hk-baslik").textContent);});
 dene("parsel tıklama (6)",()=>{const ok=E("(()=>{const p=DATA.cizimler.parselNo.find(x=>x[2]==='6');const[px,py]=HARITA.ekran(p[0],p[1]);return TIKLA_EK(p[0],p[1],px,py)})()");
  if(!ok)throw Error("isabet yok");if(!d.getElementById("hk-baslik").textContent.includes("6. Parsel"))throw Error(d.getElementById("hk-baslik").textContent);});
 dene("sonda ℹ ayrıntı",()=>{E("POP.sonda(33.5,33.8,120,120)");const b=d.querySelector("#hk-govde [data-sd]");if(!b)throw Error("ℹ yok");b.click();
  if(!d.getElementById("hk-baslik").textContent.length)throw Error("detay yok");});
 dene("FIR çizgi kartı",()=>{E('KATMAN.ac("firA",1)');E("HARITA.git(26.4,38.4,7.2)");
  const ok=E("(()=>{const s=DATA.cizimler.firAtina.find(g=>g.length>1);const p=s[0];const[px,py]=HARITA.ekran(p[0],p[1]);HARITA.git(p[0],p[1],7.4);const[qx,qy]=HARITA.ekran(p[0],p[1]);return TIKLA_EK(p[0],p[1],qx,qy)})()");
  if(!ok||!d.getElementById("hk-baslik").textContent.includes("FIR"))throw Error("["+ok+"] "+d.getElementById("hk-baslik").textContent);E('KATMAN.ac("firA",0)');});
 dene("tur: meis",()=>{E('TUR.basla("meis")');if(!d.getElementById("tur-kart").classList.contains("acik"))throw Error("kart kapalı");
  if(d.getElementById("tk-adim").textContent.trim()!=="1 / 6")throw Error(d.getElementById("tk-adim").textContent);});
 dene("tur ileri→1947",()=>{E("TUR.ileri()");if(d.getElementById("zaman-yil").textContent!=="1947")throw Error(d.getElementById("zaman-yil").textContent);});
 dene("tur bitir",()=>{E("TUR.bitir()");if(d.getElementById("tur-kart").classList.contains("acik"))throw Error("kapanmadı");});
 dene("hoşgeldin",()=>{if(d.getElementById("hosgeldin").classList.contains("gizli"))throw Error("baştan gizli");E("HG.kapa()");if(!d.getElementById("hosgeldin").classList.contains("gizli"))throw Error("kapanmadı");});
 dene("AI gizli (bağlantısız)",()=>{if(d.getElementById("btn-ai").style.display!=="none")throw Error("görünür: "+d.getElementById("btn-ai").style.display);});
 dene("✈ preset",()=>{d.getElementById("hz-hava").click();if(!E('KATMAN.g("firA")&&KATMAN.g("sarTR")'))throw Error("açılmadı");d.getElementById("hz-hava").click();});
 dene("senaryo+sıfırla hâlâ sağlam",()=>{E('SEN.uygula("ege12")');E("SEN.sifirla()");});
 dene("palet: tur+parsel",()=>{d.getElementById("palet-kutu").value="parsel";E("PALET.suz()");if(!d.querySelector("#palet-sonuc .palet-oge"))throw Error("yok");
  d.getElementById("palet-kutu").value="dakikada";E("PALET.suz()");if(!d.querySelector("#palet-sonuc .palet-oge"))throw Error("tur yok");});
 dene("ada düzeltme (Taşoz)",()=>{if(Math.abs(E('DATA.adalar.find(a=>a.id==="tasoz").lat')-40.68)>0.001)throw Error("lat eski");});
 dene("ada metni korundu",()=>{const a=E('DATA.adalar.find(a=>a.id==="meis").aciklama');if(!a||a.length<20)throw Error("metin kayıp");});
 dene("adacık karasuyu kapsıyor",()=>{if(!E('HARITA.poliIcinde([27.148,36.933],GEO.tw.gr6)'))throw Error("Pserimos gr6 dışında");});
 dene("SAR karada nokta yok",()=>{const k=E(`(()=>{let k=0;for(const seg of DATA.cizimler.sarTR)for(const p of seg)for(const pt of GEO.parts)if(HARITA.poliIcinde(p,pt.p))k++;return k})()`);if(k)throw Error(k+" nokta karada");});
 dene("FIR karada nokta yok",()=>{const k=E(`(()=>{let k=0;for(const seg of DATA.cizimler.firAtina)for(const p of seg)for(const pt of GEO.parts)if(HARITA.poliIcinde(p,pt.p))k++;return k})()`);if(k)throw Error(k+" nokta karada");});
 dene("FIR/SAR çok parçalı katman",()=>{if(E("KATMAN.geo.firA.d.length")<5)throw Error("firA parça az");if(E("KATMAN.geo.sarTR.d.length")<3)throw Error("sar parça az");});
 console.log("\n---- SONUÇ:",hatalar.length?("HATA "+hatalar.length):"V2 DUMAN TESTLERİ TEMİZ ✓");
 process.exit(hatalar.length?1:0);
},1200);
